### ISSUE TITLE
Uneven number Binary to Hex Conversion 

### ISSUE THREAD

**Issue by Shayaan-Kashif** [Shayaan-Kashif/Number-Base-Converter#1]
When converting from Binary to Hex if the input binary number is uneven the code may not work as intended. For example given the input of **10 0110 0101** the result should be **265**. However the code computes it as **4C**.  On the contrary a binary input of **010** should result in **2** and the code works given that input. 
![Screenshot 2024-09-18 at 10 37 14 PM](https://github.com/user-attachments/assets/19b75fb5-b250-45d7-8fec-600942556c7b)
![Screenshot 2024-09-18 at 10 37 03 PM](https://github.com/user-attachments/assets/0ca13f7d-92fe-45fd-9853-d49285f701c5)

**Comment by Willev05** [comment]
Line 149 is missing the % 4 operator leading to it checking if the length itself == 2. Fixed, tested and works.
![image](https://github.com/user-attachments/assets/354c84d9-3486-42b9-a88d-48d07039a0e0)
