### ISSUE TITLE
Negative fractional decimal to binary applies two's compliment to whole part, but not fractional

### ISSUE THREAD

**Issue by Willev05** [Shayaan-Kashif/Number-Base-Converter#11]
![image](https://github.com/user-attachments/assets/2a97c90e-fdf3-41e6-b4f0-2c096664e56f)
As seen in the picture, the fractional part remains unchanged. 

Something I noticed was that sites like RapidTables do not use two's compliment when dealing with fractional numbers.
![image](https://github.com/user-attachments/assets/554eed9d-2c39-4ec4-b328-56faf97ca698)

I do not know if we should cancel two's compliment when handling negative fractionals, or leave it as is.

**Comment by Shayaan-Kashif** [comment]
I believe the reason for this is because have haven't properly coded for negative floating point numbers. In the case of a decimal floating point to binary you basically get the first complement of the whole number part and fractional part and then as a whole add the 1 from the right to the left.

**Comment by Willev05** [comment]
Fixed in latest commit
