### ISSUE TITLE
To hex cannot distinguish between binary or decimal numbers only using 1 and 0

### ISSUE THREAD

**Issue by Willev05** [Shayaan-Kashif/Number-Base-Converter#4]
![image](https://github.com/user-attachments/assets/3e9e65e1-983a-4ef5-b940-250b0283444d)
As seen in the image, source base is never checked leading to the strange behaviour.

![image](https://github.com/user-attachments/assets/9742f5c9-c474-450b-b957-11833da26e45)
An if statement at line 126 can be modified and made to check the input base instead of the current approach.

**Comment by Shayaan-Kashif** [comment]
Modified the code to check what the source base is before converting
